version: '3.8'

services:
  app:
    build: .
    container_name: flowise-openai-wrapper
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - FLOWISE_API_BASE_URL=${FLOWISE_API_BASE_URL}
      - FLOWISE_CHATFLOW_ID=${FLOWISE_CHATFLOW_ID}