[build]
builder = "nixpacks"
buildCommand = "pip install poetry && poetry install --no-root"

[deploy]
startCommand = "uvicorn src.main:app --host 0.0.0.0 --port ${PORT:-8080} --workers 1"
healthcheckPath = "/"
healthcheckTimeout = 200 