[build]
builder = "nixpacks"
buildCommand = "pip install poetry && poetry install --no-root"

[deploy]
startCommand = "poetry run uvicorn src.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 200
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 5 