[build]
builder = "nixpacks"
buildCommand = "pip install poetry && poetry install --no-root"

[deploy]
startCommand = "poetry run uvicorn src.main:app --host 0.0.0.0 --port 8080"
healthcheckPath = "/"
healthcheckTimeout = 200 